const frontend6b2 = [
    {
        firstName: 'kelubia',
        lastName: 'urubusi',
        dateOfBirth: 'march 8',
        stateOfOrigin: 'Delta',
        gender: 'male',
        hobbies: ['gaming','swimming','dancing'],
    },
    {
        firstName: 'sharon',
        lastName: 'Ibanga',
        dateOfBirth: 'december 12',
        stateOfOrigin: 'akwa ibom',
        gender: 'female',
        hobbies: ['eating','sleeping','playing cards'],
    },
    {
        firstName: 'Samiat',
        lastName: 'usman',
        dateOfBirth: 'april 21',
        stateOfOrigin: 'kwara state',
        gender: 'female',
        hobbies: ['sleeping','explore','eating'],
    },
    {
        firstName: 'benson',
        lastName: 'ibe',
        dateOfBirth: 'june 3',
        stateOfOrigin: 'abia state',
        gender: 'male',
        hobbies: ['football','coding','photography'],
    },
    {
        firstName: 'chidinma',
        lastName: 'nwaneti',
        dateOfBirth: 'july 14',
        stateOfOrigin: 'anambra',
        gender: 'female',
        hobbies: ['swimming','reading novel','football'],
    },
    {
        firstName: 'thariwa',
        lastName: 'umar',
        dateOfBirth: 'april 16',
        stateOfOrigin: 'jigawa',
        gender: 'female',
        hobbies: ['reading','swimming','comedy'],
    },
    {
        firstName: 'stephen',
        lastName: 'eromosele',
        dateOfBirth: 'june 12',
        stateOfOrigin: 'edo',
        gender: 'male',
        hobbies: ['art','gaming','coding'],
    },
    {
        firstName: 'damola',
        lastName: 'Gbenga',
        dateOfBirth: 'November 18 ',
        stateOfOrigin: 'Ekiti state',
        gender: 'male',
        hobbies: ['exploring','coding','dancing'],
    },
    {
        firstName: 'Ameera',
        lastName: 'olusesi',
        dateOfBirth: 'April 24',
        stateOfOrigin: 'Lagos state',
        gender: 'female',
        hobbies: ['shopping','fashion','dancing'],
    },
    {
        firstName: 'Daniel',
        lastName: 'Danielson',
        dateOfBirth: 'August 31',
        stateOfOrigin: 'Anambra',
        gender: 'male',
        hobbies: ['smoking weed','swimming','clubing'],
    },
    {
        firstName: 'Gideon',
        lastName: 'owadara',
        dateOfBirth: 'july 17',
        stateOfOrigin: 'Ondo state',
        gender: 'male',
        hobbies: ['coding','gaming','comedy'],
    },
    {
        firstName: 'Sayo',
        lastName: 'Alabi',
        dateOfBirth: 'November 16’',
        stateOfOrigin: 'Ondo state',
        gender: 'Female',
        hobbies: ['reading', 'singing', 'writing'],
    },
    
]